#!/usr/bin/env python3


def ft_data_stream():

    from data_generator import PixelDataGenerator

    """
    This program takes information from provided data_generator. It imports
    1000 events and treats his information to print some interesting
    analytics.
    Variables:
        -total_events: number of events is going to be generated. Used to
        "fake" the timer in false_timer.
        -generator: introduce the class from data_generator to use his
        generated events.
    Functionality:
        -It introduces an stream of events to the program just to generate
        data that will be treated next.
    Return:
        -this function doesn't return anything.
    """

    def false_timer(total_events):

        """
        This function fakes the timer output showed in the subject due
        no timer function was autorized.
        Variables:
            -Time: creates a "timer" determined by the event number gived
        Functionality:
            -Divides the total events by 100000
        Return:
            -It returns the "fake time"
        """
        time = total_events / 100000

        return time

    def fibonacci(iterations):

        """
        This function creates a fibonacci secuence and gives his information
        to be treated by yield
        Variables:
            -a, b: double integer containers of the 2 numbers used in each
            iteration of the fibonacci secuence.
            -count: iterable that computes the times fibonacci has been
            iterated
        Functionality:
            -creates "iterations" first number of the fibonacci secuence and
            and sends it with yield to the printer.
        Return:
            -It doesn't return anything.
        """

        a, b = 0, 1
        count = 0

        while count < iterations:
            yield a
            a, b = b, a + b
            count += 1

    def prime_numbers(first):

        """
        This function looks for the "first" n prime_numbers.
        Variables:
            -i, j: int iterators that will check the rest of each number
            division for the numbers lower than himself
            -count: iterable that computes the times the function has found a
            prime number
        Functionality:
            -looks for the n first prime numbers
        Return:
            -It doesn't return anything.
        """

        total = 0
        i = 2
        j = 2
        while total < first:
            while j < i:
                if i % j != 0:
                    j += 1
                else:
                    i += 1
                    j = 2
            if i == j:
                yield i
                total += 1
            i += 1
            j = 2

    def game_events_stream(count=50):
        """
        This function iterates and yield the events generated by the
        data_generator
        Variables:
            -i, j: int iterators that will check the rest of each number
            division for the numbers lower than himself
            -count: iterable that computes the times the function has found a
            prime number
        Functionality:
            -looks for the n first prime numbers
        Return:
            -It doesn't return anything.
        """

        print(f"\nProcessing {count} game events...\n")

        events = generator.generate_exercise_data(5, count=count)
        for event in events:
            yield event

    def number_generator():

        """
        This function manages the generation of fibonacci and prime numbers
        Variables:
            -fibo_var, prime_var: variables that manages the number  of
            iterations the number functions will do.
            -count: iterable to manage the end of the line for both printers
        Functionality:
            -hub and printer for the secuences generators.
        Return:
            -It doesn't return anything.
        """

        fibo_var = 19
        prime_var = 10
        count = 0

        print(f"Fibonacci secuence (first {fibo_var}):", end=" ")
        for e in fibonacci(fibo_var):
            count += 1
            if count < fibo_var:
                print(e, end=", ")
            else:
                print(e, end=" ")
        count = 0
        print()
        print(f"Prime numbers (first {prime_var}):", end=" ")
        for e in prime_numbers(prime_var):
            count += 1
            if count < prime_var:
                print(e, end=", ")
            else:
                print(e, end=" ")

    def process_events(events_generated, count):

        """
        This function manages the information of the events generated
        Variables:
            -total_events: count the total events yielded by game_event_stream
            -high_level_events: count the events from player abobe level 10
            -treasure events: counts the total of treasure events generated
            -level_up_events: counts the total of times the players have
            leveled up.
            -string: recovers the end of string depending of the event chequed.
            -constant: checks if it has made a constant stream check in any
            time.
        Functionality:
            -The events stream is yield from events_generated and by a if tree
            are managed and controled.
            -After the third event, the printer stops printing just to fix the
            output to verion proposed in the subject.
            -If there was al least 1 event yielded, it prints
            "Constant (streaming)" in Memory usage.
            If it doesn't, it prints "Not in use."
        Return:
            -It doesn't return anything.
        """

        total_events = 0
        high_level_events = 0
        treasure_events = 0
        level_up_events = 0
        string = None
        constant = False

        for event in events_generated:
            total_events += 1
            constant = True
            if event['data']['level'] >= 10:
                high_level_events += 1
            if event['event_type'] == "item_found":
                string = "found treasure."
                treasure_events += 1
            if event['event_type'] == "level_up":
                string = "leveled up."
                level_up_events += 1
            if event['event_type'] == "login":
                string = "loged."
            if event['event_type'] == "logout":
                string = "loged out."
            if event['event_type'] == "kill":
                string = "killed a monter."
            if event['event_type'] == "death":
                string = "died."

            if total_events <= 3:
                print(f"Event {event['id']}: Player {event['player']}"
                      f"(level {event['data']['level']})", string)

        print(". . .")

        print("\n=== Stream Analytics ===")

        print(f"Total events processed: {total_events}")
        print(f"High level players (10+): {high_level_events}")
        print(f"Treasure events: {treasure_events}")
        print(f"Level-up events: {level_up_events}")

        if constant is True:
            print("\nMemory usage: "
                  "Constant (streaming)")
        else:
            print("\nMemory usage: "
                  "Not in use.")

    total_events = 1000
    print("\n=== Game Data Stream Processor ===\n")
    generator = PixelDataGenerator(seed=42)
    process_events(game_events_stream(total_events), total_events)
    print(f"Procesing time: {false_timer(total_events):.2f} sec")
    print("\n=== Generator Demonstration ===")
    number_generator()
    print()


if __name__ == "__main__":

    ft_data_stream()
